<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_SignIn</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>080cf8a8-8b76-4d4a-b11d-81c609882909</testSuiteGuid>
   <testCaseLink>
      <guid>46324767-0400-4bda-ae79-47e5c98f822f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_SignUp</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>93f6a6a3-ba9d-4558-ab5b-41724656a59d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_Profile</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>93f6a6a3-ba9d-4558-ab5b-41724656a59d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>User_Name</value>
         <variableId>c44cdbdd-8b85-439f-a036-af13c331bdf2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>93f6a6a3-ba9d-4558-ab5b-41724656a59d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Mail</value>
         <variableId>4a06ead9-adec-4c58-b4b0-a3785bdaa20f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>93f6a6a3-ba9d-4558-ab5b-41724656a59d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>73562fee-201a-4d59-9945-edf98f2a8b80</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>31be34fc-a74c-4055-8b2c-af739b7ba6ba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_LogIn</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3b60afa0-0f3c-41fb-920a-9f5e79e5fa6a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_Profile</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>3b60afa0-0f3c-41fb-920a-9f5e79e5fa6a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>User_Name</value>
         <variableId>e8beda83-5b0a-4036-87f0-9a245c1dd6e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3b60afa0-0f3c-41fb-920a-9f5e79e5fa6a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>0a2b33cd-e755-4c63-bba7-feee61d4bb7f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
