<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_CatLaptops</name>
   <tag></tag>
   <elementGuidId>1f1d77fe-c80f-4ae5-8962-7475f5c89fae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#laptopsTxt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='laptopsTxt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9eb0b9f7-2b12-490c-a3f5-1e99439aedbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>laptopsTxt</value>
      <webElementGuid>93000953-a4f1-4346-9636-1e9bca86ccc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>LaptopsCategoryTxt</value>
      <webElementGuid>489e3744-3ff6-4840-9a5d-e80bb96356e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shop_now roboto-bold ng-binding</value>
      <webElementGuid>5318cc20-c3a0-4500-8154-2f88cef7bb17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>6c816fc3-f207-4eef-a5f5-9ab3ebd00efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>6f2a1ae7-c9b0-4f75-a9aa-64a05656ddfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LAPTOPS</value>
      <webElementGuid>cea5a953-1eda-4775-af2a-8371f527e90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;laptopsTxt&quot;)</value>
      <webElementGuid>bd1a01b9-d0b1-4bcb-855c-a7e838957881</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='laptopsTxt']</value>
      <webElementGuid>0b40ebf4-badf-43d5-bb9d-4c3cbd718feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='laptopsImg']/div/span</value>
      <webElementGuid>ab51dd9e-d10c-46f1-aca4-d507d06d41c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span</value>
      <webElementGuid>d8871d2f-b674-4d1e-8035-58fc906226ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'laptopsTxt' and @href = 'javascript:void(0)' and (text() = 'LAPTOPS' or . = 'LAPTOPS')]</value>
      <webElementGuid>44d3fab0-f1f3-4131-90d3-a691229fb027</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
