<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_CatSpeak</name>
   <tag></tag>
   <elementGuidId>a078a166-c1bd-4582-bd6a-0bca388c7a7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#speakersTxt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='speakersTxt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ace96254-c647-476c-a57c-a2b166ed481e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>speakersTxt</value>
      <webElementGuid>22e270c2-6594-41db-90f4-e8281a37146c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>SpeakersCategoryTxt</value>
      <webElementGuid>cdf25214-2641-4b68-8e41-42396a6d21b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shop_now roboto-bold ng-binding</value>
      <webElementGuid>d82d5855-1cef-470b-8309-b59eef520f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>87a9fee3-7659-47cc-adcb-f4757267180d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>ec26eb38-e2c8-454b-8c02-bb17766ee922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SPEAKERS</value>
      <webElementGuid>983cbaeb-97da-4e92-9786-6e7ce0427223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;speakersTxt&quot;)</value>
      <webElementGuid>d6e8f9f0-6d3d-4a65-87ef-89c4b89ce3ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='speakersTxt']</value>
      <webElementGuid>3a6556b1-87c7-413a-9a85-385b9550fa9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='speakersImg']/div/span</value>
      <webElementGuid>0a4bb84d-6a9d-4ceb-9441-a0f09e867d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span</value>
      <webElementGuid>ad19f33f-8587-4675-83e1-7f482a6cef73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'speakersTxt' and @href = 'javascript:void(0)' and (text() = 'SPEAKERS' or . = 'SPEAKERS')]</value>
      <webElementGuid>73dd7e26-b22f-4286-bf26-81c8b3736043</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
