<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Price1</name>
   <tag></tag>
   <elementGuidId>3e00a90f-7af0-462b-ad68-f59b65db74e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.smollCell > p.price.roboto-regular.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shoppingCart']/table/tbody/tr[1]/td[6]/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '
                            $299.99
                        ' or . = '
                            $299.99
                        ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7fb62cc3-f7f1-450d-931a-1f3656739973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price roboto-regular ng-binding</value>
      <webElementGuid>6bc3bcf9-faab-4a6c-90e0-a573b87eacf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            $299.99
                        </value>
      <webElementGuid>123736cc-6801-416d-918d-0767eb51c982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shoppingCart&quot;)/table[@class=&quot;fixedTableEdgeCompatibility&quot;]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[@class=&quot;smollCell&quot;]/p[@class=&quot;price roboto-regular ng-binding&quot;]</value>
      <webElementGuid>a7d28a9c-b92d-4f4f-9541-cedcf13f033b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shoppingCart']/table/tbody/tr/td[6]/p</value>
      <webElementGuid>0e685026-24ce-4094-9491-9d15a3df1b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/p</value>
      <webElementGuid>e3004850-b5af-4c87-ba2d-36aa7a5175e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '
                            $299.99
                        ' or . = '
                            $299.99
                        ')]</value>
      <webElementGuid>445a1d39-9031-4496-85df-0751e1dd212e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
