<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Thanks</name>
   <tag></tag>
   <elementGuidId>31a8f8b2-86ea-4101-ad62-48529122a81f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='orderPaymentSuccess']/h2/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.roboto-regular.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1d7b04b4-25ac-4b07-a777-32aec9e02a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-regular ng-scope</value>
      <webElementGuid>ae299ecd-6e3d-4ffa-ad30-9cb74c30efd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>Thank_you_for_buying_with_Advantage</value>
      <webElementGuid>86a0eb3f-f22c-4620-81d0-72fa4bda14e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you for buying with Advantage</value>
      <webElementGuid>8071c3db-ddb1-44d6-aeb5-3472667fb8fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orderPaymentSuccess&quot;)/h2[1]/span[@class=&quot;roboto-regular ng-scope&quot;]</value>
      <webElementGuid>34c32da3-0bb1-4d0d-8e30-8ef05675acab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orderPaymentSuccess']/h2/span</value>
      <webElementGuid>64a041c3-5671-4e90-8b08-f82a04f740ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/span</value>
      <webElementGuid>0f32f54a-bc7b-4743-bba7-5b5a226dafbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Thank you for buying with Advantage' or . = 'Thank you for buying with Advantage')]</value>
      <webElementGuid>7ca67bb7-45df-48f6-9f84-4b5cb49454ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
